apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    tier: backend
    app: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      app: redis-master
  template:
    metadata:
      labels:
        tier: backend
        app: redis-master
    spec:
      containers:
        - name: master-redis-devops
          image: redis
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    tier: backend
    app: redis-master
spec:
  selector:
    tier: backend
    app: redis-master
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    tier: backend
    app: redis-slave
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
      app: redis-slave
  template:
    metadata:
      labels:
        tier: backend
        app: redis-slave
    spec:
      containers:
        - name: slave-redis-devops
          image: gcr.io/google_samples/gb-redisslave:v3
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
          env:
            - name: GET_HOSTS_FROM
              value: dns
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    tier: backend
    app: redis-slave
spec:
  selector:
    tier: backend
    app: redis-slave
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    tier: frontend
    app: guest-book
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: guest-book
  template:
    metadata:
      labels:
        tier: frontend
        app: guest-book
    spec:
      containers:
        - name: php-redis-devops
          image: "gcr.io/google-samples/gb-frontend@sha256:cbc8ef4b0a2d0b95965e0e7dc8938c270ea98e34ec9d60ea64b2d5f2df2dfbbf"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
          env:
            - name: GET_HOSTS_FROM
              value: dns
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    tier: frontend
    app: guest-book
spec:
  selector:
    tier: frontend
    app: guest-book
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
          
    