---
apiVersion: v1
kind: Service
metadata:
  namespace: iron-namespace-datacenter
  name: iron-gallery-service-datacenter
spec:
  type: NodePort
  selector:
    run: iron-gallery
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: iron-namespace-datacenter
  name: iron-gallery-deployment-datacenter 
  labels:
    run: iron-gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      run: iron-gallery
  template:
    metadata:
      labels:
        run: iron-gallery
    spec:

      volumes:
        - name: config
          emptyDir: {}
        - name: images
          emptyDir: {}

      containers:
        - name: iron-gallery-container-datacenter
          image: kodekloud/irongallery:2.0
          resources:
            limits:
              memory: 100Mi
              cpu: 50m
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/data
            - name: images
              mountPath: /usr/share/nginx/html/uploads
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: iron-namespace-datacenter
data:
  MYSQL_DATABASE: ZGF0YWJhc2VfaG9zdA==
  MYSQL_ROOT_PASSWORD: c2RmbGtqc2RmI2Rzc2ZkCg==
  MYSQL_USER: ZnVja19vcmFjbGUK
  MYSQL_PASSWORD: c2RmbGtqc2RmI2Rhc2RkCg==

---
apiVersion: v1
kind: Service
metadata:
  namespace: iron-namespace-datacenter
  name: iron-gallery-service-datacenter
spec:
  type: ClusterIP
  selector:
    db: mariadb
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: iron-namespace-datacenter
  name: iron-db-deployment-datacenter
  labels:
    db: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mariadb
  template:
    metadata:
      labels:
        db: mariadb
    spec:
      volumes:
        - name: db
          emptyDir: {}
      containers:
        - name: iron-db-container-datacenter
          image: kodekloud/irondb:2.0
          env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_DATABASE
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db
