---
apiVersion: v1
kind: Service
metadata:
  name: php-app
spec:
  type: NodePort
  selector:
    app: php
  ports:
    - port: 8093
      targetPort: 8093
      nodePort: 30012

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: nginx
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      log_format  main
              'remote_addr:$remote_addr\t'
              'time_local:$time_local\t'
              'method:$request_method\t'
              'uri:$request_uri\t'
              'host:$host\t'
              'status:$status\t'
              'bytes_sent:$body_bytes_sent\t'
              'referer:$http_referer\t'
              'useragent:$http_user_agent\t'
              'forwardedfor:$http_x_forwarded_for\t'
              'request_time:$request_time';
      access_log	/var/log/nginx/access.log main;
      server {
          listen       8093;
          server_name  _;
          root /var/www/html;
          index index.html index.htm index.php;
          location / {
            try_files $uri $uri/ =404;
          }
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-phpfpm
  labels:
    app: php
spec:
  volumes:
    - name: shared-files
      emptyDir: {}
    - name: nginx-config-volume
      configMap:
        name: nginx-config
        items:
          - key: nginx.conf
            path: nginx.conf
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 8093
      volumeMounts:
        - mountPath: /var/www/html
          name: shared-files
        - mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          name: nginx-config-volume
    - name: php-fpm-container
      image: php:7.3-fpm-alpine
      volumeMounts:
        - mountPath: /var/www/html
          name: shared-files